# Generated by Django 6.0.1 on 2026-01-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_userlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDBProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub', models.IntegerField(default=0)),
            ],
        ),
    ]
